### ISSUE TITLE
Stone suggestions to improve it

### ISSUE THREAD

**Issue by enolive** [draptik/fsharp-playground#1]
The code looks great, even for someone with little to no experience with fsharp like me. However, I'd like to suggest following improvements regarding the readability.

* Introduce an explaining constant in line 5 why you are using length minus 2
* Introduce an explaining function splitIntoChars for lines 12~14
* c in lines 31~32 has a different meaning and should be renamed to something like firstHalf and secondHalf
* inline line 22 entirely or rename c to firstCharacter
* I don't understand why line 40 is important. The algorithm should be able to handle the trivial diamond as well

**Comment by draptik** [comment]
Thanks for your feedback @enolive 
Your suggestions are good: I will try to incorporate them.

**Comment by draptik** [comment]
@enolive included all your suggestions: Code is much more F# idiomatic now, thanks again for the pointers!
